schema_version: 1

context:
  name: macchina
  version: 6.2.1
  build: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Macchina-CLI/macchina/archive/v${{ version }}.tar.gz
  sha256: 87a38bde067fadd96615899d6a8b9efdb238a4bd3859008be47b3e4c2a02c607

build:
  number: ${{ build|int + (microarch_level|int) * 100 }}
  script:
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
    - $BUILD_PREFIX/bin/cargo install --locked --root ${PREFIX} --path .

requirements:
  build:
    - if: microarch_level|int > 0
      then: x86_64-microarch-level ${{ microarch_level }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses

tests:
  - script:
      - macchina --version

about:
  homepage: https://github.com/Macchina-CLI/macchina
  documentation: https://github.com/Macchina-CLI/macchina/wiki
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fast, minimal and customizable system information frontend
  description: |
    macchina lets you view system information, like your kernel version,
    uptime, memory usage, processor load and much more. macchina is basic
    by default and extensible by design.
  repository: https://github.com/Macchina-CLI/macchina.git
